spring:
  application:
    name: ai-native-erp-poc

  datasource:
    url: jdbc:postgresql://localhost:5432/aierp_db
    username: erp_user
    password: erp_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl.create_namespaces: true

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-3-flash-preview
      embedding:
        options:
          model: gemini-embedding-001
          dimensions: 1536

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: erp-group
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.aierp.dto
        spring.json.value.default.type: com.aierp.dto.WebhookEnvelope

    listener:
      ack-mode: record
      missing-topics-fatal: false

    template:
      observation-enabled: true